### ISSUE TITLE
Issues with heads from blockdata

### ISSUE THREAD

**Issue by UWUplus** [TheWeirdSquid/Minecraft-Player-Head-Tools#1] opened 2021-05-13 23:01 UTC
All the heads have black on their transparent pixels for me. Is this an issue on my side?

Screenshot from Blender:
![Screenshot](https://sharex.host/45Uj4n73nQ.png?key=eAsYAqwc5ZiQBv)

*Blockdata:*
`{Owner:{Id:"2e1d4c02-2162-40b4-b385-fa136b17c78c",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2RhMzE5YmJlMDQ0OTMzYjg3YjlkOTE0ZjNkMjIxMDY1MTAxNGUxM2JkZDRkNDlkNGZiOTgxMGMxZDNhNDc1MSJ9fX0="}]}},SkullType:3,Rot:0}`

**Comment by DavidBootle** [comment] 2021-05-14 13:59
I believe it is an issue on your side. There is no way for the add-on to swap pixels as it basically just downloads the skin from Minecraft and applies it. You probably have some setting in your blender config that is displaying transparent pixels as black. Did you run the prep function in MCPrep?

**Comment by UWUplus** [comment] 2021-05-14 14:53
I didn't know that was needed, so I just installed the addon and ran the prep function.

But the result is still the same.

**Comment by DavidBootle** [comment] 2021-05-14 16:52
If you check the texture in the UV tab, does the texture display as transparent or black? If it's transparent, then it's your blender settings.

If that's the case, then I'm afraid I can't help you there. I'm sure a quick google for "blender displaying transparent textures as black" will help you troubleshoot it.

I've never encountered this problem when using the app, and I have multiple skins with transparent outer layers.

**Comment by DavidBootle** [comment] 2021-05-14 17:02
I've verified that the image is in fact transparent (it's [here](http://textures.minecraft.net/texture/3da319bbe044933b87b9d914f3d2210651014e13bdd4d49d4fb9810c1d3a4751)) so the problem must be with your settings. The app is pretty simple and it wouldn't be possible for it to change the image applied as the texture.

**Comment by UWUplus** [comment] 2021-05-14 17:51
> If you check the texture in the UV tab, does the texture display as transparent or black? If it's transparent, then it's your blender settings.

It looks black for me and not transparent sadly. 
![Screenshot](https://sharex.host/dAknRAGw7j.png?key=TBLXzoWdkh4bZC)

**Comment by DavidBootle** [comment] 2021-05-14 20:06
No, they are transparent. If you look closely you can see the grid behind the gray outline. If you move the image around, you'll see that it is transparent. The issue is most likely with your blender settings. I'm taking a look at it now and I'll let you know what setting worked for me.

**Comment by DavidBootle** [comment] 2021-05-14 20:12
Well turns out you were right! It was the addon. My sincerest apologies. It appears that I messed up the node setup for the material. The alpha channel for the texture is routed into emission, not alpha. If you go to the shading workspace and change the alpha to go into the alpha channel for the material, this should be fixed. I'll fix this bug in the next version of this addon. Thanks!

**Comment by DavidBootle** [comment] 2021-05-14 20:16
Here are before and after images:

Before:
<img width="772" alt="Screen Shot 2021-05-14 at 4 13 45 PM" src="https://user-images.githubusercontent.com/47395245/118324125-a1294b00-b4cf-11eb-9c86-92e1e27d6d26.png">

After:
<img width="772" alt="Screen Shot 2021-05-14 at 4 13 53 PM" src="https://user-images.githubusercontent.com/47395245/118324128-a2f30e80-b4cf-11eb-9303-d19e8e897118.png">

**Comment by UWUplus** [comment] 2021-05-14 20:30
That fixed it, thanks a lot. Is there a way I can patch this into the addon quickly or do I need to wait for an update?

**Comment by DavidBootle** [comment] 2021-05-14 22:47
MPH_add_head_model line 107 is where the issue is. The code linking node_image[1] to node_principled[18] should be node_principled[19]. However, this add on worked for blender 2.8 so I'm wondering if they added a node. If that's the case I'll have to figure out a fix for both versions. In the meantime, you can unpack the zip file, change that line, and rezip it. Then reinstall the addon and it should work. Hope that helps!

**Comment by DavidBootle** [comment] 2021-05-14 22:50
To be totally clear, the temporary fix for this is to change `[18]` to `[19]` on line 107 in the file `MPH_add_head_model.py`. This should solve the issue.

**Closed as completed** 2021-06-01 01:26 UTC

**Comment by DavidBootle** [comment] 2021-06-02 13:14
This issue has now been fixed in version 1.0.2.
